services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"           # evita conflito com um Postgres local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jyBchJmr@2005
      POSTGRES_DB: outfits
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

volumes:
  postgres_data:
